version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.mac
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - VIDEO_DEVICE=${VIDEO_DEVICE:-None}