apiVersion: v1
kind: Service
metadata:
  name: yolov8-10-ocr-service
  labels:
    app: yolov8-ocr
spec:
  type: NodePort
  selector:
    app: yolov8-ocr
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      name: streamlit
