name: MLOpsPipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: yolov8-10_ocr_app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mac]  # <- c’est ici qu’on déclare les deux cibles, jetson

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU (for cross-platform builds if needed)
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image for ${{ matrix.target }}
        run: |
          docker build -f Dockerfile.${{ matrix.target }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.target }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.target }}
